# 注释
#1- 字典格式数据---键：值
#name: tom #名字
#age: 20 #年龄
#data: 1000

#2- 列表数据
#- 10
#- 20
#- 30
#- tom

#3- 列表里面包含字典
#-
#  name: tom
#  data: 100
#  age: 20
#-
#  info: hello

##4- 字典里包含列表
#info:
#  - 10
#  - 20
#  - 30
#data:
#  - 1000
#  - 2000
#  - 3000


#5- 字典套字典
#info:
#  name: tom
#  age: 20
#data:
#  data1: 1000
#  data2: 2000


#6- 引号的处理
# （不加引号）单引号---原样输出   双引号----特殊字符显示效果
#如果数据的整形要求是字符串，必须加引号
#info: "100"
#info2: "hello\nworld"

#--- #分隔符   分割多个yaml文件
#info:
#  - 10
#  - 20
#  - 30
#---
#name: tom
#age: 20
#
#---
#- 10
#- 20

# &变量名 定义变量
# *变量名   引用变量
HOST: &HOST dfjashgfdvaslkjdfasldkfklasdfsakdjfhdlasd
url: *HOST #引用变量
